clear all
A = [ 1 1 1; 0 1 3; 0 0 1];
b = [2 -4 1]';
%% The second example from the same paper on restart GMRES.
disp('GMRES(2)')

it = 10;
r2 = zeros(3,it);
%r(k+2) = p(A)r(k). p(z) = 1 + alpha*z + beta*z^2;
r2(:,1) = b;
r2(:,2) = [3 -3 0];


for k=1:it
    alpha = ((r2(:,k)'         * A*A * r2(:,k))  * ...
             (r2(:,k)' * A'    * A*A * r2(:,k))  - ...
             (r2(:,k)'         * A*    r2(:,k))  * ...
             (r2(:,k)' * A'*A' * A*A * r2(:,k))) / ...
            ((r2(:,k)' * A'    * A   * r2(:,k))  * ...
             (r2(:,k)' * A'*A' * A*A * r2(:,k))  - ...
             (r2(:,k)' * A'    * A*A * r2(:,k))  * ...
             (r2(:,k)' * A'    * A*A * r2(:,k)));
    
   beta =  ((r2(:,k)'  *         A   * r2(:,k))  * ...
            (r2(:,k)'  * A'    * A*A * r2(:,k))  - ...
            (r2(:,k)'          * A*A * r2(:,k))  * ...
            (r2(:,k)'  * A'    * A   * r2(:,k))) / ...
           ((r2(:,k)'  * A'    * A   * r2(:,k))  * ...
            (r2(:,k)'  * A'*A' * A*A * r2(:,k))  - ...
            (r2(:,k)'  * A'    * A*A * r2(:,k))  * ...
            (r2(:,k)'  * A'    * A*A * r2(:,k)));
      
   p = eye(3) + alpha*A + beta*(A^2);
   r2(:,k+1) = p*r2(:,k);
   
end
disp(r2(:,1:end))
